# Generated by Django 5.1.2 on 2026-02-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='ml_label',
            field=models.CharField(blank=True, help_text='Etiqueta exacta usada por el modelo ML (ej: tomate_mosca_blanca)', max_length=150, null=True),
        ),
    ]
