# Generated by Django 5.1.2 on 2026-02-06 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('scientific_name', models.CharField(blank=True, help_text='Nombre científico (ej. Solanum lycopersicum)', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Descripción general del cultivo (origen, características, etc.)')),
                ('season', models.CharField(blank=True, help_text='Época o ciclo de siembra recomendado', max_length=120)),
                ('soil_type', models.CharField(blank=True, help_text='Tipo de suelo óptimo (franco, franco-arenoso, etc.)', max_length=120)),
                ('climate', models.CharField(blank=True, help_text='Clima ideal (temperatura, altitud, etc.)', max_length=120)),
                ('water_requirement', models.CharField(blank=True, help_text='Requerimiento general de agua (bajo, medio, alto)', max_length=150)),
                ('general_irrigation_notes', models.TextField(blank=True, help_text='Notas generales de riego si no hay guía específica.')),
                ('general_fertilization_notes', models.TextField(blank=True, help_text='Notas generales de fertilización para este cultivo.')),
                ('spacing_between_plants_cm', models.FloatField(blank=True, help_text='Distancia entre plantas (cm)', null=True)),
                ('spacing_between_rows_cm', models.FloatField(blank=True, help_text='Distancia entre surcos/filas (cm)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropPractice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, choices=[('establecimiento', 'Establecimiento / plántula'), ('vegetativo', 'Crecimiento vegetativo'), ('floracion', 'Floración'), ('cuajado', 'Cuajado de fruto'), ('fructificacion', 'Fructificación / llenado'), ('madurez', 'Madurez / pre-cosecha')], max_length=32)),
                ('name', models.CharField(help_text='Nombre de la práctica (ej. Poda de formación).', max_length=150)),
                ('description', models.TextField(help_text='Descripción general de la práctica.')),
                ('step_by_step', models.TextField(blank=True, help_text='Pasos recomendados (puedes usar viñetas con saltos de línea).')),
                ('safety_notes', models.TextField(blank=True, help_text='Consideraciones de seguridad y cuidado.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practices', to='chatbot.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('disease_type', models.CharField(choices=[('plaga', 'Plaga'), ('fungica', 'Fúngica'), ('bacteriana', 'Bacteriana'), ('viral', 'Viral'), ('fisiologica', 'Fisiológica'), ('otra', 'Otra')], default='plaga', max_length=50)),
                ('description', models.TextField(help_text='Descripción general de la enfermedad o plaga.')),
                ('symptoms', models.TextField(help_text='Síntomas típicos observables en el cultivo.')),
                ('causal_agent', models.CharField(blank=True, help_text='Agente causal (hongo, bacteria, insecto específico, etc.)', max_length=150)),
                ('transmission', models.TextField(blank=True, help_text='Formas de transmisión / condiciones predisponentes.')),
                ('control_cultural', models.TextField(blank=True, help_text='Medidas culturales (rotación, manejo de rastrojos, densidad, etc.)')),
                ('control_biological', models.TextField(blank=True, help_text='Control biológico (parasitoides, hongos entomopatógenos, etc.)')),
                ('control_chemical', models.TextField(blank=True, help_text='Recomendaciones químicas generales (SIN marcas comerciales).')),
                ('recommendations', models.TextField(help_text='Resumen de manejo integrado recomendado.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='chatbot.crop')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='disease_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chatbot.disease')),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(choices=[('riego', 'Riego'), ('fertilizacion', 'Fertilización'), ('plagas', 'Plagas'), ('herramientas', 'Herramientas'), ('siembra', 'Densidad / Siembra'), ('manejo', 'Manejo / Producción'), ('general', 'General')], max_length=30)),
                ('question', models.CharField(help_text='Pregunta típica del productor (tal como la haría).', max_length=300)),
                ('answer', models.TextField(help_text='Respuesta técnica y clara para mostrar en el chat.')),
                ('keywords', models.CharField(blank=True, help_text='Palabras clave separadas por coma (distancia, densidad, marco, etc.)', max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, help_text='Cultivo al que aplica (opcional para preguntas generales).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.crop')),
            ],
            options={
                'ordering': ['crop', 'topic', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FertilizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del plan (ej. Plan estándar tomate tecnificado)', max_length=150)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fertilization_plans', to='chatbot.crop')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fertilization_plans', to='chatbot.region')),
            ],
            options={
                'ordering': ['crop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FertilizationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('establecimiento', 'Establecimiento / plántula'), ('vegetativo', 'Crecimiento vegetativo'), ('floracion', 'Floración'), ('cuajado', 'Cuajado de fruto'), ('fructificacion', 'Fructificación / llenado'), ('madurez', 'Madurez / pre-cosecha')], help_text='Etapa fenológica a la que aplica', max_length=32)),
                ('npk_ratio', models.CharField(blank=True, help_text='Relación recomendada N-P-K (ej. 15-15-15, 10-30-10)', max_length=50)),
                ('source', models.CharField(blank=True, help_text='Tipo de fertilizante (ej. Urea, DAP, 15-15-15, etc.)', max_length=150)),
                ('dose_kg_ha', models.FloatField(blank=True, help_text='Dosis aproximada (kg/ha)', null=True)),
                ('applications', models.PositiveIntegerField(blank=True, help_text='Número de aplicaciones en esta etapa.', null=True)),
                ('interval_days', models.FloatField(blank=True, help_text='Intervalo entre aplicaciones (días).', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas específicas (fraccionamiento, mezclas, precauciones).')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='chatbot.fertilizationplan')),
            ],
            options={
                'ordering': ['plan', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='IrrigationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('establecimiento', 'Establecimiento / plántula'), ('vegetativo', 'Crecimiento vegetativo'), ('floracion', 'Floración'), ('cuajado', 'Cuajado de fruto'), ('fructificacion', 'Fructificación / llenado'), ('madurez', 'Madurez / pre-cosecha')], help_text='Etapa fenológica', max_length=32)),
                ('system', models.CharField(choices=[('goteo', 'Riego por goteo'), ('aspersion', 'Aspersión'), ('surcos', 'Riego por surcos'), ('microaspersores', 'Microaspersores'), ('otro', 'Otro')], help_text='Sistema de riego', max_length=32)),
                ('frequency_days', models.FloatField(blank=True, help_text='Frecuencia de riego (días entre riegos)', null=True)),
                ('volume_l_m2', models.FloatField(blank=True, help_text='Litros de agua por m² en cada riego (aprox.)', null=True)),
                ('duration_minutes', models.FloatField(blank=True, help_text='Duración de riego (minutos) si aplica (goteo/aspersión).', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas adicionales (tipo de suelo, clima, ajustes, etc.)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irrigation_guides', to='chatbot.crop')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='irrigation_guides', to='chatbot.region')),
            ],
            options={
                'ordering': ['crop', 'region', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='CropProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_yield', models.FloatField(help_text='Rendimiento promedio (toneladas/hectárea)')),
                ('practices', models.TextField(help_text='Prácticas comunes de producción (riego, poda, densidad de siembra, etc.)')),
                ('cost_estimate', models.FloatField(blank=True, help_text='Costo estimado de producción por hectárea', null=True)),
                ('market_price', models.FloatField(blank=True, help_text='Precio promedio de venta por tonelada', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_data', to='chatbot.crop')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_data', to='chatbot.region')),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Descripción y uso de la herramienta')),
                ('purpose', models.CharField(help_text='Propósito principal (siembra, poda, cosecha, riego, etc.)', max_length=150)),
                ('recommended_stage', models.CharField(blank=True, help_text='Etapa del cultivo donde se recomienda (si aplica)', max_length=120)),
                ('safety_notes', models.TextField(blank=True, help_text='Recomendaciones de seguridad al usarla.')),
                ('crop', models.ForeignKey(blank=True, help_text='Opcional: herramienta asociada a un cultivo concreto.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='chatbot.crop')),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('fertilizacion', 'Fertilización'), ('herramientas', 'Herramientas'), ('tecnicas', 'Técnicas de producción'), ('manejo', 'Manejo/Buenas prácticas'), ('plagas', 'Plagas y enfermedades'), ('otros', 'Otros')], db_index=True, max_length=32)),
                ('subtopic', models.CharField(blank=True, choices=[('riego', 'Riego'), ('plan_fertilizacion', 'Plan de fertilización'), ('poda', 'Poda'), ('cosecha', 'Cosecha'), ('suelo', 'Manejo de suelo'), ('uso_herramientas', 'Uso de herramientas'), ('control_plagas', 'Control de plagas'), ('general', 'General')], help_text='Tema más específico (riego, poda, fertilización, etc.)', max_length=32)),
                ('specific_question', models.CharField(blank=True, help_text="Pregunta típica que responde este artículo (ej. '¿cómo regar tomate en floración?').", max_length=300)),
                ('difficulty', models.CharField(blank=True, choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], help_text='Nivel técnico del contenido.', max_length=50)),
                ('tags', models.CharField(blank=True, max_length=250)),
                ('summary', models.CharField(blank=True, help_text='Resumen corto para mostrar en el chat.', max_length=300)),
                ('key_points', models.TextField(blank=True, help_text='Puntos clave (pueden ser viñetas separadas por saltos de línea).')),
                ('content', models.TextField(help_text='Contenido completo del artículo.')),
                ('tools_text', models.TextField(blank=True, help_text='Texto libre de herramientas mencionadas (si aplica).')),
                ('sources', models.TextField(blank=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.crop')),
                ('disease', models.ForeignKey(blank=True, help_text='Opcional: artículo asociado a una enfermedad/plaga concreta.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.disease')),
                ('tool', models.ForeignKey(blank=True, help_text='Opcional: artículo asociado a una herramienta específica.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.tool')),
            ],
            options={
                'ordering': ['-updated_at', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('predicted_disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.disease')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detected_stage', models.CharField(blank=True, choices=[('establecimiento', 'Establecimiento / plántula'), ('vegetativo', 'Crecimiento vegetativo'), ('floracion', 'Floración'), ('cuajado', 'Cuajado de fruto'), ('fructificacion', 'Fructificación / llenado'), ('madurez', 'Madurez / pre-cosecha')], max_length=32)),
                ('detected_intent', models.CharField(blank=True, help_text='Ej. riego, fertilizacion, plagas, herramientas...', max_length=50)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detected_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='chatbot.crop')),
                ('attached_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.uploadedimage')),
            ],
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['crop', 'disease_type'], name='chatbot_dis_crop_id_db9cd2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='irrigationguide',
            unique_together={('crop', 'region', 'stage', 'system')},
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['category', 'is_published'], name='chatbot_kno_categor_5c1cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgearticle',
            index=models.Index(fields=['crop', 'category'], name='chatbot_kno_crop_id_d1abba_idx'),
        ),
    ]
