# Generated by Django 5.1.2 on 2026-03-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_disease_ml_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='ml_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
