# Generated by Django 5.1.2 on 2026-02-10 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('unidad_medida', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('ton', 'Toneladas'), ('unidad', 'Unidad'), ('caja', 'Caja'), ('bulto', 'Bulto')], default='kg', max_length=10)),
                ('cantidad_disponible', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_unitario', models.CharField(blank=True, max_length=50, null=True)),
                ('calidad', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('municipio', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_disponibilidad', models.DateField(blank=True, null=True)),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen_secundaria', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('pausado', 'Pausado')], default='disponible', max_length=15)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.categoria')),
            ],
        ),
    ]
