# Generated by Django 5.1.2 on 2026-02-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_codigoemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productor',
            name='tipo_cultivo',
        ),
        migrations.AddField(
            model_name='productor',
            name='categorias_cultivo',
            field=models.CharField(blank=True, help_text='Ej: frutas,verduras', max_length=200),
        ),
        migrations.AddField(
            model_name='productor',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
