# Generated by Django 5.1.2 on 2026-02-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_remove_productor_tipo_cultivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='perfiles/default.png', null=True, upload_to='perfiles/'),
        ),
    ]
