# Generated by Django 5.1.2 on 2026-03-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0004_alter_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
